sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install mypy
    - pip install numpy
    - pip install pylint

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - make travis
